name: Test Clear All Notifications URI

on:
  workflow_dispatch:

jobs:
  test_clear_all_notifications_uri:
    runs-on: windows-latest
    steps:
      - name: Checkout ClassIsland repository
        uses: actions/checkout@v3

      - name: Checkout EdgeTtsSharp repository
        uses: actions/checkout@v3
        with:
          repository: ClassIsland/EdgeTtsSharp
          path: vendors/EdgeTtsSharp

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build ClassIsland
        run: dotnet build ClassIsland/ClassIsland.csproj -c Release

      - name: Run ClassIsland
        run: Start-Process -FilePath "ClassIsland/bin/Release/net8.0-windows/ClassIsland.exe"

      - name: Wait for ClassIsland to start
        run: Start-Sleep -Seconds 10

      - name: Call clearAllNotifications URI
        run: explorer "classisland://app/clearAllNotifications"

      - name: Wait for URI to be processed
        run: Start-Sleep -Seconds 5
